Complaintapp/urls.py
from django.conf.urls import url
from Complaintapp import views

app_name="Complaintapp"

urlpatterns=[
    url(r'^homepage/$',views.HomePage,name='homepage'),
    url(r'^about/$',views.About,name='about'),
    url(r'^info/$',views.Info,name='info'),
    url(r'^warden/$',views.Warden,name='warden'),
    url(r'^details/$',views.Details,name='details'),
]

Complaintproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from Complaintapp import views
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title='Warden Panel'

urlpatterns = [
    url(r"^$",views.HomePage,name='homepage'),
    url(r"^Complaintapp/",include("Complaintapp.urls",namespace="Complaintapp")),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Complaintapp/models.py
from django.db import models

# Create your models here.
class ComplaintInfo(models.Model):
    name=models.CharField(max_length=255)
    email=models.EmailField(unique=True,null=True)
    year=models.CharField(max_length=90)
    enrollment_num=models.IntegerField(unique=True)
    room_num=models.IntegerField(unique=True)
    complaintbox=models.TextField(max_length=255)

    def __str__(self):
        return self.name

class WardenInfo(models.Model):
    image=models.ImageField(upload_to="media", blank=True)
    warden_name=models.CharField(max_length=255,null=True)
    designation=models.CharField(max_length=255,null=True)

    def __str__(self):
        return self.warden_name

Complaintapp/forms.py
from django import forms
from Complaintapp.models import ComplaintInfo

class InfoForm(forms.ModelForm):
    class Meta():
        model=ComplaintInfo
        fields="__all__"

Complaintapp/views.py
from django.shortcuts import render
from Complaintapp.forms import InfoForm
from Complaintapp.models import WardenInfo,ComplaintInfo
from django.contrib import messages

def base(request):
    return render(request,'Complaintapp/base.html')

def HomePage(request):
    return render(request,'Complaintapp/homepage.html')

def About(request):
    return render(request,'Complaintapp/about.html')

def Warden(request):
    img = WardenInfo.objects.all()
    return render(request,'Complaintapp/warden.html',{"img":img})

def SuccessComplaint(request):
    return render(request,'Complaintapp/successcomplaint.html')


def Info(request):
    form=InfoForm()
    if request.method=='POST':
        form = InfoForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request,'HII')
            return SuccessComplaint(request)
        else:
            print("error")
    return render(request,'Complaintapp/information.html',{'form':form})

def Details(request):
    complaints=ComplaintInfo.objects.all()
    mydict={'mycomplaints':complaints}
    return render(request,'Complaintapp/complaintdetails.html',context=mydict)

templates/Complaintapp/about.html
{%extends 'Complaintapp/base.html'%}
{%block body_block%}
{%load staticfiles%}
<link rel="stylesheet" href="{%static 'css/about.css'%}">
	<div class="container">
		<div class="about">
			<div class="text">
				<h1>About Us</h1>
				<div class="line"></div>
			</div>
		</div>
		<div class="content">
			<p>We are here for helping you to give your complains of hostel directly
				to your Warden.Problems related your Rooms,Ragging,RoomChanging etc
			</p>
		</div>
		</div>
    <footer>&copy;Created by: Deepak Shakya</footer>
{%endblock%}

templates/Complaintapp/base.html
<!DOCTYPE html> {%load staticfiles%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Complaint Portal</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Satisfy" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{%static 'css/base.css'%}">
</head>

<body>

    <body>
        <nav class="navbar navbar-default techfont custom-navbar">
            <div class="container">
                <ul class="nav nav-pills col-md-9">
                    <li role="presentation"><a href="{%url 'Complaintapp:homepage'%}">Home</a></li>
                    <li role="presentation"><a href="{%url 'Complaintapp:about'%}">About</a></li>
                    <li role="presentation"><a href="{%url 'Complaintapp:warden'%}">Warden Details</a></li>
                    <li role="presentation"><a href="{%url 'Complaintapp:details'%}">Complaint Details</a></li>

                </ul>
            </div>
        </nav>


        {%block body_block%} {%endblock%}



    </body>

</html>

templates/Complaintapp/complaintdetails.html
{%extends 'Complaintapp/base.html'%} {%block body_block%} {%load staticfiles%}
<link rel="stylesheet" href="{%static 'css/detail.css'%}"> {%if mycomplaints%}
<h1 style="text-align: center; font-weight: bold;margin-top: 70px; margin-bottom:0;">Complaint Details</h1>
<table>
    <tr>
        <th>S.NO</th>
        <th>Name</th>
        <th>Year</th>
        <th>Enrollment No.</th>
        <th>Room No.</th>
        <th>Complains</th>
    </tr>

    {%for list in mycomplaints%}
    <tr>
        <td class="list">{{list.id}}</td>
        <td class="list">{{list.name}}</td>
        <td class="list">{{list.year}}</td>
        <td class="list">{{list.enrollment_num}}</td>
        <td class="list">{{list.room_num}}</td>
        <td class="list">{{list.complaintbox}}</td>
    </tr>
    {%endfor%} {%else%} print("error") {%endif%} {%endblock%}

templates/Complaintapp/homepage.html
{%extends 'Complaintapp/base.html'%} {%block body_block%} {%load staticfiles%}
<link rel="stylesheet" href="{%static 'css/homepage.css'%}">
<div class="container-fluid blok1">
    <div class="text col-md-6">
        <h1 class="display-4" style="font-size: larger;"><strong>Any Problem!Regarding to Hostel</strong></h1>
        <div class="line"></div>
        <p><em>Give your Complain Here!</em></p>
        <a class="link" href="{%url 'Complaintapp:info'%}"><span>Click Here!</span></a>
    </div>
</div>
<footer>&copy;Created by: Deepak Shakya</footer>
{%endblock%}

templates/Complaintapp/information.html
{%extends 'Complaintapp/base.html'%} {%block body_block%} {%load staticfiles%} {% load bootstrap3 %}
<link rel="stylesheet" href="{%static 'css/info.css'%}" />
<form class="jumbotron" method="post">
    <fieldset>
        <h2 class="fs-title">Fill your Complaints!</h2>
        {%csrf_token%} {%bootstrap_form form%}
        <input type="submit" class="btn btn-primary action-button btn-lg" value="Submit" />
    </fieldset>
</form>
{% if messages%}
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<footer class="page-footer font-big">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3" style="font-weight: bold; font-size: large; padding: 20px;">
        &copy;2020 Created by: Deepak Shakya
    </div>
    <!-- Copyright -->
</footer>
{%endblock%}

templates/Complaintapp/successcomplaint.html
{%extends 'Complaintapp/base.html'%} {%block body_block%} {%load staticfiles%}
<div class="alert alert-success" role="alert" style="text-align: center; margin:-1.5em;   width:101%; ">
    <h1><strong>Your Complaint is Successfully submitted to Warden Panel!</strong></h1>
    <p style="font-size: large;"><strong>Go to <a href="{%url 'Complaintapp:homepage'%}">Home</a> for further Complaints</strong></p>
</div>
{%endblock%}

templates/Complaintapp/warden.html
{%extends 'Complaintapp/base.html'%} {%block body_block%} {%load staticfiles%}
<link rel="stylesheet" href="{%static 'css/warden.css'%}">
<div class="flex-container">
    {%for i in img%}
    <div>
        <img src="{{i.image.url}}" width="400">
        <p>Name:{{i.warden_name}}</p>
        <p>Designation:{{i.designation}}</p>
    </div>
    {%endfor%}
</div>
{%endblock%}